### ISSUE TITLE
Release into maven central?

### ISSUE THREAD

**Issue by nielsbasjes** [jborgers/PMD-jPinpoint-rules#179]
My suggestion is to release the rulesets/java/jpinpoint-rules.xml wrapped in a versioned jar file into maven central.

The reason is that projects that want to use your rules can then do something like this (partially tested example):

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-pmd-plugin</artifactId>
  <version>${maven-pmd-plugin.version}</version>
  <dependencies>
    <dependency>
      <groupId>io.github.jborgers</groupId>
      <artifactId>PMD-jPinpoint-rules</artifactId>
      <version>1.2.3</version>
    </dependency>
  </dependencies>
  <configuration>
    <rulesets>
      <!-- The JPinpoint ruleset -->
      <ruleset>/rulesets/java/jpinpoint-rules.xml</ruleset>
    </rulesets>
  </configuration>
  <executions>
    <execution>
      <id>validate bugs</id>
      <phase>validate</phase>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

With that projects can use tools like renovate or dependabot to automate updating the rules.

Possibly useful tooling to make this as easy as possible:
https://github.com/semantic-release/semantic-release
https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages

**Comment by emouty** [comment]
With the breaking changes introduced with pmd 7.x.x and the work on https://github.com/jborgers/PMD-jPinpoint-rules/tree/pmd7-upgrade-7.2.0 this would be a nice to have :smiley:

**Comment by jborgers** [comment]
The plugin for Sonar is available from maven central: https://central.sonatype.com/artifact/com.jpinpoint.sonar/sonar-pmd-jpinpoint

**Comment by nielsbasjes** [comment]
Thanks!

I just now tried adding this code fragment to my pom.xml 

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-pmd-plugin</artifactId>
  <version>3.23.0</version>
  <dependencies>
    <dependency>
      <groupId>com.jpinpoint.sonar</groupId>
      <artifactId>sonar-pmd-jpinpoint</artifactId>
      <version>2.0.0</version>
    </dependency>
  </dependencies>
  <configuration>
    <rulesets>
      <!-- The JPinpoint ruleset -->
      <ruleset>/com/jpinpoint/pmd/rules/jpinpoint-rules.xml</ruleset>
    </rulesets>
  </configuration>
  <executions>
    <execution>
      <id>validate bugs</id>
      <phase>prepare-package</phase>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>

```

and I got a lot of errors and stacktraces from the PMD plugin (which does say `[INFO] PMD version: 7.0.0`).

`java.lang.ClassCastException: class net.sf.saxon.value.Int64Value cannot be cast to class net.sf.saxon.value.StringValue (net.sf.saxon.value.Int64Value and net.sf.saxon.value.StringValue are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @31d51518)
`
and 

`net.sourceforge.pmd.lang.rule.xpath.PmdXPathException: net.sf.saxon.trans.XPathException: Cannot compare xs:integer to xs:integer`

When I comment out the configuration of the rulesets I simply get a few PMD violations.

Am I doing something wrong here?

**Comment by nielsbasjes** [comment]
```
java.lang.ClassCastException: class net.sf.saxon.value.Int64Value cannot be cast to class net.sf.saxon.value.StringValue (net.sf.saxon.value.Int64Value and net.sf.saxon.value.StringValue are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @35a27c09)
        at net.sf.saxon.expr.sort.CodepointCollatingComparer.comparesEqual(CodepointCollatingComparer.java:109)
        at net.sf.saxon.expr.ValueComparison.compare(ValueComparison.java:404)
        at net.sf.saxon.expr.GeneralComparison.compare(GeneralComparison.java:856)
        at net.sf.saxon.expr.GeneralComparison.evaluateManyToMany(GeneralComparison.java:776)
        at net.sf.saxon.expr.GeneralComparison.effectiveBooleanValue(GeneralComparison.java:657)
        at net.sf.saxon.expr.FilterIterator$NonNumeric.matches(FilterIterator.java:180)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:77)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:63)
        at net.sf.saxon.om.FocusTrackingIterator.next(FocusTrackingIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:63)
        at net.sf.saxon.om.FocusTrackingIterator.next(FocusTrackingIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:63)
        at net.sf.saxon.om.FocusTrackingIterator.next(FocusTrackingIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:63)
        at net.sf.saxon.om.FocusTrackingIterator.next(FocusTrackingIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.getNextMatchingItem(FilterIterator.java:76)
        at net.sf.saxon.expr.FilterIterator.next(FilterIterator.java:63)
        at net.sourceforge.pmd.lang.rule.xpath.internal.SaxonXPathRuleQuery.evaluate(SaxonXPathRuleQuery.java:127)
        at net.sourceforge.pmd.lang.rule.xpath.XPathRule.apply(XPathRule.java:101)
        at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.applyOnIndex(RuleApplicator.java:77)
        at net.sourceforge.pmd.lang.rule.internal.RuleApplicator.apply(RuleApplicator.java:57)
        at net.sourceforge.pmd.lang.rule.internal.RuleSets.apply(RuleSets.java:155)
        at net.sourceforge.pmd.lang.impl.PmdRunnable.processSource(PmdRunnable.java:140)
        at net.sourceforge.pmd.lang.impl.PmdRunnable.run(PmdRunnable.java:80)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by stokpop** [comment]
@nielsbasjes Hi Niels, thank for reporting and the suggestion of using the `pmd-maven-plugin` together with the jPinpoint rules!

I tried this on my machine, but do no see the ClassCastException you report. 

What versions of Java and maven are you using? I did a run with java 17 and maven 3.9.9 and with: 

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.26.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.jpinpoint.sonar</groupId>
                        <artifactId>sonar-pmd-jpinpoint</artifactId>
                        <version>2.0.0</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-core</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>net.sourceforge.pmd</groupId>
                        <artifactId>pmd-java</artifactId>
                        <version>${pmd.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <rulesets>
                        <!-- The JPinpoint ruleset -->
                        <ruleset>/com/jpinpoint/pmd/rules/jpinpoint-rules.xml</ruleset>
                    </rulesets>
                </configuration>
                <executions>
                    <execution>
                        <id>validate bugs</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

By setting `pmd.version` you can also run more recent versions, like `7.14.0` (`7.7.0` is default in maven-pmd-plugin `3.26.0`).

also added this to add line number links in the report:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jxr-plugin</artifactId>
                <version>3.6.0</version>
            </plugin>
```

And run with: `mvn clean compile jxr:jxr pmd:pmd`

With debugging the maven session I saw that it is using: `Saxon-HE-12.5.jar` from this classloader: 

```
ClassRealm[plugin>org.apache.maven.plugins:maven-pmd-plugin:3.26.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@42110406]
``` 

Does running pmd from command line work for your project?

**Comment by nielsbasjes** [comment]
I'm going to retry this and provide a reproduction.
